-- Seed data migrated from the frontend's src/data/site.js
-- Run with: mysql -u root -p technical_journals < backend/database/seed.sql
USE technical_journals;

-- ============================================================
-- UNIVERSITIES
-- ============================================================
INSERT INTO universities (name, slug, country, logo, journals_count, website_url, description, status, display_order, featured) VALUES
('University of Oxford', 'university-of-oxford', 'United Kingdom', NULL, 12, 'https://www.ox.ac.uk', NULL, 'active', 1, 1),
('National University of Singapore', 'national-university-of-singapore', 'Singapore', NULL, 8, 'https://www.nus.edu.sg', NULL, 'active', 2, 1),
('The University of Melbourne', 'the-university-of-melbourne', 'Australia', NULL, 9, 'https://www.unimelb.edu.au', NULL, 'active', 3, 1),
('University of Toronto', 'university-of-toronto', 'Canada', NULL, 15, 'https://www.utoronto.ca', NULL, 'active', 4, 1),
('Technical University of Munich', 'technical-university-of-munich', 'Germany', NULL, 7, 'https://www.tum.de', NULL, 'active', 5, 1),
('University of Cape Town', 'university-of-cape-town', 'South Africa', NULL, 6, 'https://www.uct.ac.za', NULL, 'active', 6, 1),
('University of Sydney', 'university-of-sydney', 'Australia', NULL, 5, 'https://www.sydney.edu.au', NULL, 'active', 7, 1),
('King''s College London', 'kings-college-london', 'United Kingdom', NULL, 7, 'https://www.kcl.ac.uk', NULL, 'active', 8, 1);

-- ============================================================
-- JOURNALS
-- ============================================================
INSERT INTO journals (slug, title, subject_area, category, issn, indexing, frequency, access_type, language, university_id, color, icon, status, featured, description, about, aims_scope, review_type) VALUES
('international-journal-of-computer-science-and-engineering', 'International Journal of Computer Science and Engineering', 'Computer Science', 'Engineering', '2454-9940', 'Scopus', 'Quarterly', 'Open Access', 'English', 1, 'from-sky-900 to-slate-900', 'Cpu', 'active', 1, 'A leading peer-reviewed journal covering advances in computer science and engineering.', 'Publishes original research across algorithms, systems, and software engineering.', 'Covers theoretical and applied computer science research of international significance.', 'Double Blind Review'),
('journal-of-environmental-studies', 'Journal of Environmental Studies', 'Environmental Science', 'Science', '2455-8821', 'Scopus', 'Bi-Monthly', 'Open Access', 'English', 2, 'from-green-800 to-green-950', 'Leaf', 'active', 1, 'Research on environmental science, sustainability and climate policy.', 'Focuses on interdisciplinary environmental research.', 'Welcomes studies on ecology, climate change and sustainability.', 'Double Blind Review'),
('journal-of-electrical-and-electronics-engineering', 'Journal of Electrical and Electronics Engineering', 'Electrical Engineering', 'Engineering', '2454-4782', 'Scopus', 'Quarterly', 'Open Access', 'English', 3, 'from-amber-700 to-orange-950', 'Zap', 'active', 1, 'Covering advancements in electrical and electronics engineering.', 'Publishes research in power systems, circuits, and control.', 'Aims to disseminate research in electrical and electronics engineering.', 'Single Blind Review'),
('international-journal-of-mechanical-engineering', 'International Journal of Mechanical Engineering', 'Mechanical Engineering', 'Engineering', '2456-1290', 'WoS', 'Bi-Monthly', 'Open Access', 'English', 4, 'from-red-800 to-red-950', 'Cog', 'active', 0, 'Mechanical engineering research and applications.', 'Focused on thermal, mechanical and manufacturing systems.', 'Covers mechanical design, manufacturing and materials.', 'Double Blind Review'),
('journal-of-advanced-materials-research', 'Journal of Advanced Materials Research', 'Materials Science', 'Science', '2455-5999', 'Scopus', 'Quarterly', 'Open Access', 'English', 5, 'from-violet-800 to-purple-950', 'Atom', 'active', 0, 'Advanced materials science research.', 'Explores novel materials and nanotechnology.', 'Covers synthesis, characterization and applications of materials.', 'Double Blind Review'),
('international-journal-of-biotechnology-research', 'International Journal of Biotechnology Research', 'Biotechnology', 'Science', '2456-7741', 'UGC', 'Bi-Monthly', 'Subscription', 'English', 6, 'from-cyan-800 to-blue-950', 'Dna', 'active', 0, 'Biotechnology and life sciences research.', 'Publishes work in genetic engineering and molecular biology.', 'Covers biotechnology applications in medicine and agriculture.', 'Single Blind Review'),
('journal-of-information-technology-and-systems', 'Journal of Information Technology and Systems', 'Information Technology', 'Engineering', '2455-0300', 'Scopus', 'Quarterly', 'Open Access', 'English', 7, 'from-slate-800 to-slate-950', 'Network', 'active', 1, 'Information technology and systems research.', 'Focuses on IT infrastructure, networks and data systems.', 'Covers information systems, cybersecurity and networking.', 'Double Blind Review'),
('international-journal-of-civil-engineering', 'International Journal of Civil Engineering', 'Civil Engineering', 'Engineering', '2454-8642', 'UGC', 'Bi-Monthly', 'Open Access', 'English', 8, 'from-blue-900 to-slate-900', 'Building2', 'active', 0, 'Civil engineering and infrastructure research.', 'Covers structural, geotechnical and transportation engineering.', 'Publishes research on sustainable infrastructure development.', 'Single Blind Review'),
('journal-of-mathematics-and-applied-sciences', 'Journal of Mathematics and Applied Sciences', 'Mathematics', 'Science', '2456-1963', 'Scopus', 'Quarterly', 'Open Access', 'English', 1, 'from-emerald-800 to-green-950', 'Sigma', 'active', 0, 'Pure and applied mathematics research.', 'Covers mathematical theory and applied statistics.', 'Publishes original research in mathematics and applied sciences.', 'Double Blind Review'),
('international-journal-of-chemical-engineering', 'International Journal of Chemical Engineering', 'Chemical Engineering', 'Engineering', '2455-9983', 'Scopus', 'Quarterly', 'Open Access', 'English', 4, 'from-teal-800 to-cyan-950', 'FlaskConical', 'active', 0, 'Chemical engineering process and design research.', 'Focused on process engineering and chemical reactions.', 'Covers chemical process design, catalysis and materials.', 'Double Blind Review');

-- ============================================================
-- CONFERENCES
-- ============================================================
INSERT INTO conferences (slug, code, title, conference_type, subject_area, organizer, description, topics, start_date, end_date, display_date, location, city, country, region, venue, conference_mode, registration_url, color, status, featured) VALUES
('international-conference-on-artificial-intelligence-and-applications-icai-2025', 'ICAI 2025', 'International Conference on Artificial Intelligence and Applications (ICAI 2025)', 'International Conference', 'Computer Science', 'University of Oxford', 'Exploring the latest breakthroughs and applications in Artificial Intelligence and Machine Learning.', 'Artificial Intelligence,Machine Learning,Data Science,Robotics', '2025-07-15', '2025-07-17', '15 - 17 July, 2025', 'Oxford, United Kingdom', 'Oxford', 'United Kingdom', 'Europe', 'University of Oxford', 'In-Person', 'https://www.technicaljournals.org/conferences/icai-2025', 'bg-blue-900', 'active', 1),
('international-conference-on-civil-engineering-icce-2025', 'ICCE 2025', 'International Conference on Civil Engineering (ICCE 2025)', 'International Conference', 'Civil Engineering', 'Technical University of Munich', 'Innovations and sustainable practices in civil engineering for a resilient future.', 'Structural Engineering,Sustainability,Transportation,Geotechnics', '2025-09-10', '2025-09-12', '10 - 12 September, 2025', 'Munich, Germany', 'Munich', 'Germany', 'Europe', 'Technical University of Munich', 'In-Person', 'https://www.technicaljournals.org/conferences/icce-2025', 'bg-green-800', 'active', 1),
('international-conference-on-electrical-technology-icet-2025', 'ICET 2025', 'International Conference on Electrical Technology (ICET 2025)', 'International Conference', 'Electrical Engineering', 'University of Melbourne', 'Advancements in electrical technologies and power systems for modern world.', 'Power Systems,Smart Grid,Renewable Energy,Control Systems', '2025-10-22', '2025-10-24', '22 - 24 October, 2025', 'Melbourne, Australia', 'Melbourne', 'Australia', 'Oceania', 'University of Melbourne', 'In-Person', 'https://www.technicaljournals.org/conferences/icet-2025', 'bg-purple-800', 'active', 0),
('international-conference-on-computer-science-iccs-2025', 'ICCS 2025', 'International Conference on Computer Science (ICCS 2025)', 'International Conference', 'Computer Science', 'National University of Singapore', 'Cutting-edge research in computer science and its real-world applications.', 'Algorithms,Computer Networks,Cyber Security,Software Engineering', '2025-11-05', '2025-11-07', '5 - 7 November, 2025', 'Singapore', 'Singapore', 'Singapore', 'Asia', 'National University of Singapore', 'In-Person', 'https://www.technicaljournals.org/conferences/iccs-2025', 'bg-orange-700', 'active', 1),
('international-conference-on-mechanical-engineering-icme-2026', 'ICME 2025', 'International Conference on Mechanical Engineering (ICME 2026)', 'International Conference', 'Mechanical Engineering', 'University of Toronto', 'Innovative technologies and materials shaping the future of mechanical engineering.', 'Thermal Engineering,Materials Science,Manufacturing,Mechatronics', '2026-01-14', '2026-01-16', '14 - 16 January, 2026', 'Toronto, Canada', 'Toronto', 'Canada', 'North America', 'University of Toronto', 'In-Person', 'https://www.technicaljournals.org/conferences/icme-2026', 'bg-teal-800', 'active', 0);
